// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFf4YoE2CAmTByu7CZPlGAOrppwfS2TJo',
    appId: '1:214450361951:web:dcd4f99a6495daa709edea',
    messagingSenderId: '214450361951',
    projectId: 'no-so-simple-chat-app',
    authDomain: 'no-so-simple-chat-app.firebaseapp.com',
    storageBucket: 'no-so-simple-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRD1qzjVmSvl8R0ghwEMhVlFr5Zaf6gE',
    appId: '1:214450361951:android:25f9b48fd9819a4909edea',
    messagingSenderId: '214450361951',
    projectId: 'no-so-simple-chat-app',
    storageBucket: 'no-so-simple-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtjrpRhLbdaSUEUP_HsUcpCClJ-h3RUcQ',
    appId: '1:214450361951:ios:714cbb730385428209edea',
    messagingSenderId: '214450361951',
    projectId: 'no-so-simple-chat-app',
    storageBucket: 'no-so-simple-chat-app.firebasestorage.app',
    iosBundleId: 'com.notso.simple.chat.notSoSimpleChatApp',
  );
}
